"""Single entry point: run every CAPSM Stage-1 phase in order and write
`results/SUMMARY.md` with a single consolidated results table.

Usage:
    python scripts/run_all.py            # run phases 0..6 in order
    python scripts/run_all.py --skip 0   # skip phase 0 (real-data download)
    python scripts/run_all.py --only 4 5 6
    python scripts/run_all.py --test     # also run the unit-test suite
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
RESULTS = ROOT / "results"

PHASES = {
    0: ("phase0_data.py",        "Verified download + integrity report"),
    1: ("phase1_data.py",        "Real-data layer: cache, sanity figures, ramp mining"),
    2: ("phase2_grid.py",        "QSTS grid environment on real data (all IEEE cases)"),
    3: ("phase3_baselines.py",   "Baseline controllers on real Jan 2019 data"),
    4: ("phase4_system1.py",     "System 1 CNN-LSTM training + evaluation"),
    5: ("phase5_system2.py",     "System 2 QIRL evaluation"),
    6: ("phase6_arbiter.py",     "Full CAPSM integration (System 1 + 2 + Arbiter)"),
}


def run_phase(n: int, script_name: str) -> tuple[bool, float, str]:
    script_path = SCRIPTS / script_name
    t0 = time.time()
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=ROOT,
        env={"PYTHONPATH": str(ROOT), "PATH": "/usr/bin:/bin:/usr/local/bin"},
        capture_output=True, text=True,
    )
    dt = time.time() - t0
    out = (proc.stdout or "") + "\n" + (proc.stderr or "")
    ok = proc.returncode == 0
    excerpt = out.strip().splitlines()[-40:] if ok else out.strip().splitlines()[-60:]
    return ok, dt, "\n".join(excerpt)


def load_summary(n: int) -> dict:
    path = RESULTS / f"phase{n}" / f"phase{n}_summary.json"
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


def write_summary_md(phase_reports: list[dict]) -> None:
    RESULTS.mkdir(parents=True, exist_ok=True)
    out = RESULTS / "SUMMARY.md"
    lines = [
        "# CAPSM Stage-1 — Consolidated Results",
        "",
        "Auto-generated by `scripts/run_all.py`. Re-run with:",
        "```bash",
        "python scripts/run_all.py",
        "```",
        "",
        "## Phase-by-phase summary",
        "",
        "| Phase | Description | Status | Runtime (s) |",
        "|---|---|---|---|",
    ]
    for r in phase_reports:
        status = "PASS" if r["ok"] else "FAIL"
        lines.append(f"| {r['phase']} | {r['desc']} | {status} | {r['runtime_s']:.1f} |")
    lines.append("")

    p6 = load_summary(6)
    if p6:
        lines += [
            "## Headline result — controller comparison (Jan 2019, IEEE 39-bus, 721 h)",
            "",
            "| Controller | Mean losses (MW) | Mean \\|V−1\\| (p.u.) | Violations (bus-h) | Converged | Inference (ms/step) |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        order = ["no_control", "rule_based", "pid", "system1", "system2", "capsm"]
        labels = {
            "no_control": "NoControl", "rule_based": "RuleBased", "pid": "PID",
            "system1": "System 1 (CNN-LSTM)", "system2": "System 2 (QIRL)",
            "capsm": "CAPSM (Arbiter)",
        }
        base = p6.get("no_control", {}).get("voltage_violation_hours")
        for k in order:
            if k not in p6:
                continue
            s = p6[k]
            delta = ""
            if base is not None and k != "no_control":
                d = s["voltage_violation_hours"] - base
                pct = 100 * d / base if base else 0
                delta = f" ({d:+d} h, {pct:+.2f}%)"
            lines.append(
                f"| {labels[k]} | {s['mean_losses_mw']:.2f} | {s['mean_voltage_dev_pu']:.4f} | "
                f"{s['voltage_violation_hours']}{delta} | "
                f"{s['converged']}/{s['n_steps']} | {s['ms_per_step']:.1f} |"
            )
        lines.append("")

    p2 = load_summary(2)
    if p2:
        lines += [
            "## QSTS convergence (real OPSD profiles)",
            "",
            "| Case | Steps | Converged |",
            "|---|---:|---:|",
        ]
        for k, v in p2.items():
            if isinstance(v, dict) and "n_steps" in v:
                lines.append(f"| {k} | {v['n_steps']} | {v['converged']} |")
        lines.append("")

    p3 = load_summary(3)
    if p3 and "no_control" in p3:
        nc = p3["no_control"]
        lines += [
            "## Baseline economics (Jan 2019, case39)",
            "",
            f"- Energy cost (NoControl): {nc['energy_cost_meur']:.3f} MEUR",
            f"- Loading margin at valley: {nc.get('loading_margin_valley')}×",
            f"- Loading margin at peak:  {nc.get('loading_margin_peak')}×",
            f"- Renewable curtailment hours: {nc.get('curtailment_hours')} h (90% cap)",
            "",
        ]

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[run_all] summary written to {out}")


def main():
    parser = argparse.ArgumentParser(description="Run all CAPSM Stage-1 phases.")
    parser.add_argument("--only", type=int, nargs="+", help="Run only these phase numbers (0-6)")
    parser.add_argument("--skip", type=int, nargs="+", default=[])
    parser.add_argument("--test", action="store_true")
    args = parser.parse_args()

    todo = [n for n in PHASES if n not in args.skip]
    if args.only:
        todo = [n for n in todo if n in args.only]
    todo.sort()

    print(f"[run_all] running phases: {todo}")
    phase_reports = []
    for n in todo:
        script, desc = PHASES[n]
        print(f"\n[run_all] === Phase {n}: {desc} ({script}) ===")
        ok, dt, log = run_phase(n, script)
        phase_reports.append({"phase": n, "desc": desc, "ok": ok,
                              "runtime_s": dt, "log": log})
        print(f"[run_all] phase {n}: {'PASS' if ok else 'FAIL'} in {dt:.1f}s")
        if not ok:
            print("--- log excerpt ---")
            print(log)
            print("--- end log ---")

    write_summary_md(phase_reports)

    if args.test:
        print("\n[run_all] === running pytest suite ===")
        proc = subprocess.run(
            [sys.executable, "-m", "pytest", str(ROOT / "tests"), "-q"],
            cwd=ROOT,
            env={"PYTHONPATH": str(ROOT), "PATH": "/usr/bin:/bin:/usr/local/bin"},
            capture_output=True, text=True,
        )
        print(proc.stdout)
        if proc.returncode != 0:
            print(proc.stderr, file=sys.stderr)

    n_pass = sum(1 for r in phase_reports if r["ok"])
    n_fail = len(phase_reports) - n_pass
    print(f"\n[run_all] {n_pass}/{len(phase_reports)} phases passed, {n_fail} failed")
    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
